print('-=-' * 11)
print(' Classificação Brasileirão 2024')
print('-=-' * 11)
times = ('Botafogo', 'Flamengo', 'Palmeiras', 'Fortaleza', 'Cruzeiro', 'São Paulo', 'Bahia', 'Athletico-PR', 'Bragantino', 'Atlético-MG', 'Juventude', 'Vasco')
print('Lista de times: {}'.format(times))
print('Times em ordem alfabética: {}'.format(sorted(times)))
print('Os 4 primeiros são: {}'.format(times[0:4]))
print('Os 4 últimos são: {}'.format(times[8:12]))
print('O Vasco está na posicão {}'.format(times.index('Vasco')))